# The basic colors
foreground               #d4be98
background               #1d2021
selection_foreground     #1d2021
selection_background     #3c3836

# Cursor colors
cursor                   #d4be98
cursor_text_color        #1d2021

# URL underline color when hovering with mouse
urlcolor             #a9b665

# Kitty window border colors
activebordercolor   #7daeao3
inactivebordercolor #505a60
bellbordercolor     #8d8a6f

# OS window titlebar colors
waylandtitlebarcolor system
macostitlebarcolor   system

# Tab bar colors
activetabforeground   #1d2021
activetabbackground   #d4be98
inactivetabforeground #d8b98c
inactivetabbackground #28302a
tabbarbackground      #1d2021

# Colors for marks (marked text in the terminal)
mark1foreground #1d2021
mark1background #7daeao3
mark2foreground #1d2021
mark2background #d3869b
mark3foreground #1d2021
mark3_background #89b482

# The 16 terminal colors
# black
color0  #1d2021
color8  #665c54

# red
color1  #ea6962
color9  #ea6962

# green
color2  #a9b665
color10 #a9b665

# yellow
color3  #d8a657
color11 #d8a657

# blue
color4  #7daea3
color12 #7daea3

# magenta
color5  #d3869b
color13 #d3869b

# cyan
color6  #89b482
color14 #89b482

# white
color7  #d4be98
color15 #ddc7a1
